name: Create Release on Tag and Test Pass

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.8'
          distribution: 'adopt'

      - name: Set up Gradle 8.2.1
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2.1-bin.zip
          unzip -d /opt/gradle gradle-8.2.1-bin.zip
          export PATH=$PATH:/opt/gradle/gradle-8.2.1/bin

      - name: Run tests
        run: |
          ./gradlew test --tests com.laundry.laundryMgmt.MachineTest.MachineDaoTest

      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: build/docs

      - name: Archive sources
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: src

      - name: Create Documentation ZIP
        run: zip -r build/docs/documentation.zip build/docs

      - name: Create Sources ZIP
        run: zip -r src/sources.zip src

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release created automatically by GitHub Actions.
            Download the documentation [here](https://github.com/rdpetrelv/TestBackend/releases/download/${{ github.ref }}/documentation.zip).
            Download the source code [here](https://github.com/rdpetrelv/TestBackend/releases/download/${{ github.ref }}/sources.zip).
          draft: false
          prerelease: false


