name: Create Release on Tag and Test Pass

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.8'
          distribution: 'adopt'

      - name: Set up Gradle 8.2.1
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2.1-bin.zip
          unzip -d /opt/gradle gradle-8.2.1-bin.zip
          export PATH=$PATH:/opt/gradle/gradle-8.2.1/bin

      - name: Run tests
        run: |
          ./gradlew test --tests com.laundry.laundryMgmt.MachineTest.MachineDaoTest

      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: ./build/docs

      - name: Archive sources
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: ./src

      - name: Generate Changelog
        run: |
          TAG=$(git describe --tags --abbrev=0)
          git log --pretty=format:"%s" $TAG..HEAD > CHANGELOG.md

      - name: Archive Changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: ./CHANGELOG.md

      - name: Create Documentation ZIP
        run: zip -r build/docs/documentation.zip build/docs

      - name: Create Sources ZIP
        run: zip -r src/sources.zip src

      - name: Create Release
        id: create_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.MY_ACCESS_TOKEN }}
          file: |
            build/docs/documentation.zip
            src/sources.zip
            CHANGELOG.md
          asset_name: |
            documentation.zip
            sources.zip
            CHANGELOG.md
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            Release created automatically by GitHub Actions.