name: Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.8'
          distribution: 'adopt'

      - name: Set up Gradle 8.2.1
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2.1-bin.zip
          unzip -d /opt/gradle gradle-8.2.1-bin.zip
          export PATH=$PATH:/opt/gradle/gradle-8.2.1/bin

      - name: Build Javadoc
        run: |
          ./gradlew javadoc 

      - name: Create Documentation Folder
        run: mkdir -p ./build/docs/javadoc-folder

      - name: Copy Files to Documentation Folder
        run: cp -R ./build/docs/javadoc/* ./build/docs/javadoc-folder/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:  ${{ secrets.MY_ACCESS_TOKEN }}
          publish_dir: ./build/docs/javadoc-folder
          keep_files: true
          publish_branch: gh-pages