name: Release on Tag and Test Pass

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.8'
          distribution: 'adopt'

      - name: Set up Gradle 8.2.1
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2.1-bin.zip
          unzip -d /opt/gradle gradle-8.2.1-bin.zip
          export PATH=$PATH:/opt/gradle/gradle-8.2.1/bin

      - name: Run tests
        run: |
          ./gradlew test --tests com.laundry.laundryMgmt.MachineTest.MachineDaoTest

      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: ./docs

      - name: Archive sources
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: ./src

      - name: Get last tag
        id: get_last_tag
        run: |
          last_tag=$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1))
          echo ::set-output name=last_tag::$last_tag

      - name: Debug tags
        run: |
          git fetch --tags
          git tag -l

      - name: Generate Changelog
        id: generate_changelog
        run: |
          last_tag=${{ steps.get_last_tag.outputs.last_tag }}
          changelog=$(git log --pretty=format:"- %s" $last_tag..${{ github.ref }})
          echo "Commits between $last_tag and ${{ github.ref }}:"
          git log $last_tag..${{ github.ref }} --oneline
          if [ -z "$changelog" ]; then
            echo "Changelog is empty. No commits found in the specified range."
            exit 1
          fi
          echo "$changelog" > CHANGELOG.md

      - name: Debug info after generate_changelog
        run: cat CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release created automatically by GitHub Actions.

            Changelog:
            $(cat CHANGELOG.md)
          draft: false
          prerelease: false

      - name: Get Release ID
        id: get_release_id
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.MY_ACCESS_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref }}" | jq -r '.id')
          echo "Release ID: $RELEASE_ID"

      - name: Update Release with Changelog
        uses: softprops/action-gh-release@v1
        with:
          files: CHANGELOG.md
          release_id: ${{ steps.get_release_id.outputs.RELEASE_ID }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
          token: ${{ secrets.MY_ACCESS_TOKEN }}
